### ISSUE TITLE
Windows10対応(Docker on windows use WSL2)

### ISSUE THREAD

**Issue by hryktrd** [okyawa/elasticsearch-docker-test#1]
Windows10環境(WSL2)ではバーチャルメモリの容量が足りないというエラーが出たので以下の記事を参考に設定を修正したので共有します。
https://stackoverflow.com/questions/42111566/elasticsearch-in-windows-docker-image-vm-max-map-count

* ```wsl -d docker-desktop``` としてDocker用のディストリビューションに入る
* ```sysctl -w vm.max_map_count=262144``` としてバーチャルメモリの値を上げる
* ```echo "vm.max_map_count = 262144" > /etc/sysctl.d/99-docker-desktop.conf``` として起動時から有効になるように設定

これでDocker on windows(WSL2)でdocker-compose upができるようになりました。

**Comment by okyawa** [comment]
@hryktrd 
READMEに追記しました。
共有ありがとうございます！
